###################
### CONFIG VARS ###
###################

# RBENV
rbenv_root: /usr/local/rbenv
ruby_version: 2.3.2

#NGINX
config_file_path: files/nginx.conf

#DB SETUP
db_name: ruby_server_db
db_user: ruby_developer
db_user_password: developer